-- 시헌테크 A/S 홈페이지: 장비 모델 관리자 기능 설치 SQL
-- Supabase > SQL Editor에서 이 파일 전체를 1회 실행하세요.

create table if not exists public.equipment_models (
  id bigint generated by default as identity primary key,
  category text not null,
  manufacturer text not null,
  model text not null,
  sort_order integer not null default 999,
  created_at timestamptz not null default now(),
  constraint equipment_models_unique unique (category, manufacturer, model)
);

create index if not exists equipment_models_category_idx on public.equipment_models(category);
create index if not exists equipment_models_manufacturer_idx on public.equipment_models(category, manufacturer);

alter table public.equipment_models enable row level security;

drop policy if exists "equipment_models public read" on public.equipment_models;
create policy "equipment_models public read"
on public.equipment_models for select
to anon, authenticated
using (true);

drop policy if exists "equipment_models authenticated insert" on public.equipment_models;
create policy "equipment_models authenticated insert"
on public.equipment_models for insert
to anon, authenticated
with check (true);

drop policy if exists "equipment_models authenticated update" on public.equipment_models;
create policy "equipment_models authenticated update"
on public.equipment_models for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "equipment_models authenticated delete" on public.equipment_models;
create policy "equipment_models authenticated delete"
on public.equipment_models for delete
to anon, authenticated
using (true);

insert into public.equipment_models (category, manufacturer, model, sort_order) values
('잉크젯 프린터','캐논','GX 공통',10),('잉크젯 프린터','캐논','GX5090시리즈',20),('잉크젯 프린터','캐논','GX6090시리즈',30),('잉크젯 프린터','캐논','GX7090시리즈',40),
('잉크젯 프린터','HP','HP 공통 (A4)',50),('잉크젯 프린터','HP','HP 공통 (A3)',60),('잉크젯 프린터','HP','OJ7720',70),('잉크젯 프린터','HP','OJ7740',80),('잉크젯 프린터','HP','OJ9730',90),('잉크젯 프린터','HP','OJ9120',100),('잉크젯 프린터','HP','OJ8710',110),('잉크젯 프린터','HP','OJ8210',120),
('잉크젯 프린터','앱손','앱손 공통',130),('잉크젯 프린터','앱손','L6270',140),
('레이저 프린터','캐논','캐논 공통',150),('레이저 프린터','캐논','C3725',160),('레이저 프린터','캐논','C3826',170),('레이저 프린터','캐논','C3926',180),
('레이저 프린터','삼성','삼성 공통',190),('레이저 프린터','삼성','X3220',200),('레이저 프린터','삼성','X4300',210),
('레이저 프린터','리코','리코 공통',220),('레이저 프린터','리코','C2010',230),('레이저 프린터','리코','C2510',240),('레이저 프린터','리코','C3510',250),('레이저 프린터','리코','IM2500',260),('레이저 프린터','리코','IM3000',270),
('공기청정기','웰리핏','SH-3025',280),('공기청정기','웰리핏','SH-4025',290)
on conflict (category, manufacturer, model) do nothing;
